services:
  game-api:
    container_name: "${APP_NAME:-game-api}"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: indiegabo/${APP_NAME:-game-api}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=development
  mysql:
        container_name: mysql-${APP_NAME:-game-api}
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - "mysql-data:/var/lib/mysql"
            - "./docker/mysql/create-api-database.sh:/docker-entrypoint-initdb.d/10-create-api-database.sh"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
volumes:
    mysql-data:
        driver: local