/**
 * Enumerates lifecycle states for launcher versions.
 *
 * Numeric values intentionally align with existing sg_versions state values
 * already persisted in database records.
 */
export enum LauncherVersionState {
    /**
     * Version has been generated by CI/CD and is waiting release approval.
     */
    ReleaseCandidate = 4,

    /**
     * Version has been officially released to the public channel.
     */
    Released = 5,

    /**
     * Version has been rejected and should not be released.
     */
    Rejected = 7,

    /**
     * Version is deprecated and should not be used.
     */
    Deprecated = 8,
}
